debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.tonykang22.ordinaryboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: tony
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_branch_fetch_size: 100
  sql.init.mode: always

